title: Grace Gillis's Homepage
page-top-title: Grace Gillis
top-section-bg-text:
bg-copyright:  '&copy; University of Oxford Images / John Cairns Photography'
home-subtitle: Grace Gillis
copyright-text: '&copy; Grace Gillis 2024. All Rights Reserved.'
